// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebsterWebApp.Data;

namespace WebsterWebApp.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20211229060335_CreateIdentitySchema")]
    partial class CreateIdentitySchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebsterWebApp.Areas.Admin.Models.CandidateList", b =>
                {
                    b.Property<int>("CandidateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.HasKey("CandidateId");

                    b.HasIndex("Email");

                    b.ToTable("tb_Candidate_List");
                });

            modelBuilder.Entity("WebsterWebApp.Areas.Admin.Models.User", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Email");

                    b.ToTable("tb_User");
                });

            modelBuilder.Entity("WebsterWebApp.Areas.Admin.Models.CandidateList", b =>
                {
                    b.HasOne("WebsterWebApp.Areas.Admin.Models.User", null)
                        .WithMany("CandidateLists")
                        .HasForeignKey("Email");
                });

            modelBuilder.Entity("WebsterWebApp.Areas.Admin.Models.User", b =>
                {
                    b.Navigation("CandidateLists");
                });
#pragma warning restore 612, 618
        }
    }
}
